name:                haskell-sandbox
version:             0.1.0.0
github:              "jhmcstanton/haskell-sandbox"
license:             BSD3
author:              "Jim McStanton"
maintainer:          "jim@jhmcstanton.com"
copyright:           "2019 Jim McStanton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            experimental

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jhmcstanton/haskell-sandbox#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-sandbox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-sandbox

tests:
  haskell-sandbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-sandbox
